    
spring:
  config:
    import: optional:configserver:http://localhost:4000
  application:
    name: account-service

  boot:
    admin:
      client:
        url: http://localhost:4142

management:
  endpoints:
    web:
      exposure:
        include: '*'    